spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          resource-id: springboot-keycloak-client

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: '8081'
  servlet:
    context-path: /api