version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    volumes:
      - db-data:/var/lib/postgresql/data
    container_name: lab04-db

  keycloak:
    image: michelemorgigno/keycloak_g35:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    container_name: lab04-keycloak

  server:
    image: lab04-server:latest
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/SpringBootKeycloak
    container_name: lab04-server

volumes:
  db-data:
